# Generated by Django 4.0.3 on 2022-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.TextField(),
        ),
    ]
