# Generated by Django 4.0.3 on 2022-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('objective', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_joined', models.DateField(blank=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
